import type { Provider } from "../types"

export const mockProviders: Provider[] = [
  {
    id: "pt-001",
    name: "Bis FagQ",
    category: "Electrician",
    location: "Cape Coast",
    rating: 5.0,
    reviewCount: 127,
    completionRate: 0.98,
    verified: true,
    description: "Expert in electrical appliances and home wiring. 10+ years of experience with residential and commercial projects.",
    availability: "Available Now",
    quickSlots: ["Today 2PM", "Today 5PM", "Tomorrow 9AM"],
    phone: "+233241234567",
    whatsapp: "+233241234567",
    serviceAreas: ["Cape Coast", "Elmina", "Saltpond"],
    skills: ["Wiring", "Appliance Repair", "Panel Installation"],
    joinedDate: "2022-01-15"
  },
  {
    id: "pt-002",
    name: "Ama Brown",
    category: "Cleaner",
    location: "Accra",
    rating: 5.0,
    reviewCount: 89,
    verified: false,
    description: "Professional house cleaning specialist. Deep cleaning, regular maintenance, and office cleaning services.",
    availability: "Available Now",
    quickSlots: ["Today 3PM", "Tomorrow 10AM", "Tomorrow 2PM"],
    phone: "+233241234568",
    whatsapp: "+233241234568",
    serviceAreas: ["Accra", "Tema", "East Legon"],
    skills: ["Deep Cleaning", "Office Cleaning", "Window Cleaning"],
    joinedDate: "2023-03-20"
  },
  {
    id: "pt-003",
    name: "Kwame Mensah",
    category: "Plumber",
    location: "Kumasi",
    rating: 4.8,
    reviewCount: 156,
    completionRate: 0.95,
    verified: true,
    description: "Licensed plumber specializing in pipe installation, leak repairs, and bathroom renovations.",
    availability: "Available Soon",
    quickSlots: ["Tomorrow 8AM", "Tomorrow 1PM", "Tomorrow 4PM"],
    phone: "+233241234569",
    whatsapp: "+233241234569",
    serviceAreas: ["Kumasi", "Ejisu", "Bekwai"],
    skills: ["Pipe Installation", "Leak Repair", "Bathroom Renovation"],
    joinedDate: "2021-06-10"
  },
  {
    id: "pt-004",
    name: "Sarah Osei",
    category: "Handyman",
    location: "Accra",
    rating: 4.9,
    reviewCount: 203,
    completionRate: 0.97,
    verified: true,
    description: "Versatile handyman for all your home repair needs. Furniture assembly, mounting, and general repairs.",
    availability: "Available Now",
    quickSlots: ["Today 4PM", "Today 6PM", "Tomorrow 11AM"],
    phone: "+233241234570",
    whatsapp: "+233241234570",
    serviceAreas: ["Accra", "Tema", "Spintex"],
    skills: ["Furniture Assembly", "Mounting", "General Repairs"],
    joinedDate: "2020-11-05"
  },
  {
    id: "pt-005",
    name: "Emmanuel Asante",
    category: "Carpenter",
    location: "Takoradi",
    rating: 4.7,
    reviewCount: 94,
    verified: true,
    description: "Custom furniture maker and carpenter. Specializes in cabinets, shelves, and custom woodwork.",
    availability: "Available Now",
    quickSlots: ["Today 1PM", "Tomorrow 9AM", "Tomorrow 3PM"],
    phone: "+233241234571",
    whatsapp: "+233241234571",
    serviceAreas: ["Takoradi", "Sekondi", "Elubo"],
    skills: ["Custom Furniture", "Cabinets", "Woodwork"],
    joinedDate: "2022-08-12"
  },
  {
    id: "pt-006",
    name: "Grace Adjei",
    category: "Painter",
    location: "Tema",
    rating: 4.9,
    reviewCount: 78,
    completionRate: 0.99,
    verified: true,
    description: "Professional interior and exterior painter. High-quality finishes and color consultation available.",
    availability: "Available Soon",
    quickSlots: ["Tomorrow 7AM", "Tomorrow 12PM", "Tomorrow 5PM"],
    phone: "+233241234572",
    whatsapp: "+233241234572",
    serviceAreas: ["Tema", "Accra", "Ashaiman"],
    skills: ["Interior Painting", "Exterior Painting", "Color Consultation"],
    joinedDate: "2023-01-18"
  }
]

